### ISSUE TITLE
Put Travis-CI for Sprinkler

### ISSUE THREAD

**Issue by shantanoo-desai** [ComNets-Bremen/TWIN#20]
* Put __Travis-CI__ check on the `Sprinkler` Module.

Travis-CI cannot emulate a Raspberry Pi but basic check to see if code is running, depending whether future upgrades need to be done on the protocol itself. 

### Requirements for Travis YML file

1. `before-script` : `pre-check.sh` which makes necessary folder (`logFiles`) and file (`Sprinkler.log') and a folder `incoming` with a dummy file `incomingCheck.tar`

2. `run`: use `timeout` for __I<sub>max</sub>__ to see if script is run. (assuming `coreutils` on Travis servers have `timeout`)

**Comment by jdede** [comment]
Does this really make sense? We can check the parameters but as far as I know the essential part cannot be checked: The protocol operating on a real wireless interface. So we can use Travis to ensure the build / includes etc. are working not if the complete system will run as expected. Or am I missing important points?

**Comment by shantanoo-desai** [comment]
yes, agreed. Only if someone wishes to change the complete mechanism then maybe a check would be required.
Closing it.
